### ISSUE TITLE
Player turning (while shooting and thrusting).

### ISSUE THREAD

**Issue by elijahscherz** [elijahscherz/astroshooter-2d#1]
When the player is shooting and moving forward, they can't turn left for some reason.

Only on Windows, according to tests by @s0mbieZ 

Need to check with Adam and David on whether they get the glitch.

**Comment by s0mbieZ** [comment]
yeh

**Comment by s0mbieZ** [comment]
@elijahscherz I cannot replicate this bug.  Was it inadvertently fixed somehow?

**Comment by elijahscherz** [comment]
@s0mbieZ For some reason, it still occurs for me, but only when using arrow keys on Windows. I am going to have both Adam and David test it, see if it is just an problem that I am having personally.
