### ISSUE TITLE
While shielded you cannot be added lives.

### ISSUE THREAD

**Issue by elijahscherz** [elijahscherz/astroshooter-2d#14]
I know the fix, just need to implement. These issues are an amazing way to remind me.

**Comment by s0mbieZ** [comment]
@elijahscherz wait can you pick up other powerups when shielded?

**Comment by elijahscherz** [comment]
@s0mbieZ I am not actually sure if it applies to all, I am quite sure it at least applies to some of them.

**Comment by elijahscherz** [comment]
Whoops! It looks like I was wrong about this, I haven't been able to get it to do it again so.
