### ISSUE TITLE
"Dead in the water"

### ISSUE THREAD

**Issue by s0mbieZ** [elijahscherz/astroshooter-2d#3]
# Description:

The "dead in the water" bug occurs in many different circumstances.  When this bug occurs, the player is unable to move or fire, and is sometimes invincible to certain situations which would usually cause death.  The glitch can also cause the invincibility cloak to stay on longer than normal, or the booster animation to play when the player is not moving.
# Cases:

% = sometimes causes bug
@ = always causes bug
<----------------------------------------------------------------------------------->
% being shot by a flying saucer while invincible cloak is still on
% spawning on top of a large rock with the invincibility cloak on
...more causes will be added as they are observed...

hold on tight, this one's gonna be a doozy

**Comment by elijahscherz** [comment]
@s0mbieZ This is actually super helpful, thanks a lot.

**Comment by elijahscherz** [comment]
As far as I can tell, if you are currently "inside" two or more objects (may only take one) when the shield is powered down, (meaning the Collider2D is colliding with another Collider2D) then the game is unsure what to do, and freezes the player.

**Comment by s0mbieZ** [comment]
@elijahscherz Ok, well maybe the best way to go about this is to handle the error rather then prevent it.  Can you figure out a way to detect when this situation is present (the `Collider2D` is colliding with another `Collider2D`) and then cause a different response?  Maybe moving or destroying one of the `Collider2Ds`?  I don't know what the proper response would be.  The point is: maybe this bug would be better resolved by handling the error rather then preventing it from happening in the first place.

**Comment by elijahscherz** [comment]
Enlightening idea. I will look into it, and get back with the deets. @s0mbieZ
