### ISSUE TITLE
When shielded, saucer bullets are lethal.

### ISSUE THREAD

**Issue by elijahscherz** [elijahscherz/astroshooter-2d#5]
Pretty sure that somehow, even when you are shielded the saucer's still manage to shoot you. (Even when Collider2D is disabled?)

Look into this. (I mean this as a note to me, and @s0mbieZ if you have noticed anything.)

**Comment by s0mbieZ** [comment]
@elijahscherz yes this is definitely a problem, and I suspect that it is a side effect of a larger bug that also causes the "dead in the water bug".  If you can figure out what it is, it might fix many other bugs also.
