### ISSUE TITLE
Player starts with 0 lives when restarting after a loss

### ISSUE THREAD

**Issue by s0mbieZ** [elijahscherz/astroshooter-2d#8]
When the player hits enter to start a new game, the lives counter shows 0, even though the player actually has 3 lives

@elijahscherz I did some debugging, here's what you need to do to fix this bug:
add 

``` C#
UpdateLives (0);
```

to the `GameStart()` method

That's it!  The problem was that `livesText` was not being updated at the start of a new game.

**Comment by elijahscherz** [comment]
@s0mbieZ Sickkk, fixing the issue now.
